version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: slub-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - save_cache:
          key: slub-{{ .Branch }}
          paths:
            - ~/.m2
      - run:
          name: "Running build"
          command: ./run.sh
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} ~/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ~/junit/
          destination: artifacts
      - store_test_results:
          path: ~/junit/
          destination: testartifacts